#ccflags-y += -Wall
	
#ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/msg2xxx/
#ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/

obj-y += ilitek_drv_main.o \
	ilitek_drv_sprd.o \
	ilitek_drv_update.o \



