#
# Makefile for the fingerprint drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_ICNT_FINGERPRINT)   += fpsensor/
obj-$(CONFIG_ET310_FINGERPRINT_TEE) += et310_tee/
obj-$(CONFIG_GOODIX_FINGERPRINT) += gdspi/
obj-$(CONFIG_BETTERLIFE_FINGERPRINT) += betterlife_fp/
obj-$(CONFIG_SUNWAVE_FINGERPRINT) += sunwave/
