/*------this is auto generated by build engine, it is for native Feature/Default Value build config, Please do not modify manually------*/
#ifndef _SPR_TARGET_H_
#define _SPR_TARGET_H_


#define MODULES_PROJECT_CUSTOMER_NAME    "Tplink"
#define MODULES_PROJECT_CUSTOMER_SKU    "Tplink"
#define MODULES_PROJECT_NAME    "E5526T"
#define BUILD_RO_BUILD_DISPLAY_ID    "C7s_V09_20191021"
#define BUILD_HARDWARE_VERSION    "V3.0"
#define BUILD_RO_PRODUCT_MODEL    "Neffos C7s"
#define NATIVE_DISPLAY_NAME_BT_PRODUCT    "Neffos C7s"
#define NATIVE_DISPLAY_NAME_CAMERA_VENDOR    "TP-Link"
#define NATIVE_DISPLAY_NAME_CAMERA_MODEL    "Neffos C7s"
#define NATIVE_DISPLAY_NAME_GADGET_VENDOR    "TP-Link"
#define NATIVE_DISPLAY_NAME_GADGET_PRODUCT    "Neffos C7s"
#define NATIVE_DISPLAY_NAME_MTP_VENDOR    ""
#define NATIVE_DISPLAY_NAME_MTP_PRODUCT    "Neffos C7s"
#define SPR_COUNTRY_CODE_FEATURE_NATIVE    

#endif
